"""initial schema

Revision ID: 78ae56f30d1a
Revises:
Create Date: 2026-07-26 10:49:44.978925

"""

from __future__ import annotations

from collections.abc import Sequence

import sqlalchemy as sa
from alembic import op

# revision identifiers, used by Alembic.
revision: str = "78ae56f30d1a"
down_revision: str | Sequence[str] | None = None
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "archive_record",
        sa.Column("id", sa.Integer(), autoincrement=True, nullable=False),
        sa.Column("session_id", sa.String(), nullable=False),
        sa.Column("summary", sa.Text(), nullable=False),
        sa.Column("period_start", sa.String(), nullable=False),
        sa.Column("period_end", sa.String(), nullable=False),
        sa.Column("created_at", sa.String(), nullable=False),
        sa.PrimaryKeyConstraint("id"),
    )
    with op.batch_alter_table("archive_record", schema=None) as batch_op:
        batch_op.create_index(batch_op.f("ix_archive_record_session_id"), ["session_id"], unique=False)

    op.create_table(
        "memory_record",
        sa.Column("id", sa.Integer(), autoincrement=True, nullable=False),
        sa.Column("layer", sa.String(), nullable=False),
        sa.Column("category", sa.String(), nullable=False),
        sa.Column("key", sa.String(), nullable=False),
        sa.Column("value", sa.Text(), nullable=False),
        sa.Column("created_at", sa.String(), nullable=False),
        sa.Column("updated_at", sa.String(), nullable=False),
        sa.Column("expires_at", sa.String(), nullable=True),
        sa.PrimaryKeyConstraint("id"),
    )
    with op.batch_alter_table("memory_record", schema=None) as batch_op:
        batch_op.create_index(batch_op.f("ix_memory_record_key"), ["key"], unique=False)
        batch_op.create_index(batch_op.f("ix_memory_record_layer"), ["layer"], unique=False)

    op.create_table(
        "topic_history",
        sa.Column("id", sa.Integer(), autoincrement=True, nullable=False),
        sa.Column("topic_id", sa.String(), nullable=False),
        sa.Column("last_used_at", sa.String(), nullable=False),
        sa.Column("use_count", sa.Integer(), nullable=False),
        sa.Column("engaged_count", sa.Integer(), nullable=False),
        sa.PrimaryKeyConstraint("id"),
    )
    with op.batch_alter_table("topic_history", schema=None) as batch_op:
        batch_op.create_index(batch_op.f("ix_topic_history_topic_id"), ["topic_id"], unique=True)

    op.create_table(
        "usage",
        sa.Column("id", sa.Integer(), autoincrement=True, nullable=False),
        sa.Column("plugin", sa.String(), nullable=False),
        sa.Column("type", sa.String(), nullable=False),
        sa.Column("date", sa.String(), nullable=False),
        sa.Column("tokens", sa.Integer(), nullable=True),
        sa.PrimaryKeyConstraint("id"),
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table("usage")
    with op.batch_alter_table("topic_history", schema=None) as batch_op:
        batch_op.drop_index(batch_op.f("ix_topic_history_topic_id"))

    op.drop_table("topic_history")
    with op.batch_alter_table("memory_record", schema=None) as batch_op:
        batch_op.drop_index(batch_op.f("ix_memory_record_layer"))
        batch_op.drop_index(batch_op.f("ix_memory_record_key"))

    op.drop_table("memory_record")
    with op.batch_alter_table("archive_record", schema=None) as batch_op:
        batch_op.drop_index(batch_op.f("ix_archive_record_session_id"))

    op.drop_table("archive_record")
    # ### end Alembic commands ###
