"""split usage tokens

Revision ID: 27385c0c4fbb
Revises: 78ae56f30d1a
Create Date: 2026-07-26 16:39:05.246519

"""

from __future__ import annotations

from collections.abc import Sequence

import sqlalchemy as sa
from alembic import op

from muika.config import get_name_from_config

# revision identifiers, used by Alembic.
revision: str = "27385c0c4fbb"
down_revision: str | Sequence[str] | None = "78ae56f30d1a"
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table("usage", schema=None) as batch_op:
        batch_op.add_column(sa.Column("model", sa.String(), nullable=False, server_default=""))
        batch_op.add_column(sa.Column("input_tokens", sa.Integer(), nullable=True))
        batch_op.add_column(sa.Column("output_tokens", sa.Integer(), nullable=True))
        batch_op.add_column(sa.Column("cached_tokens", sa.Integer(), nullable=True))

    default_model = get_name_from_config()

    op.execute(
        sa.text(
            "UPDATE usage"
            " SET input_tokens = CAST(COALESCE(tokens, 0) * 0.7 AS INTEGER),"
            " output_tokens = COALESCE(tokens, 0) - CAST(COALESCE(tokens, 0) * 0.7 AS INTEGER),"
            " cached_tokens = 0,"
            " model = :model"
        ).bindparams(sa.bindparam("model", default_model))
    )

    with op.batch_alter_table("usage", schema=None) as batch_op:
        batch_op.drop_column("tokens")

    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # Step 1: 重新添加 tokens 列
    with op.batch_alter_table("usage", schema=None) as batch_op:
        batch_op.add_column(sa.Column("tokens", sa.Integer(), nullable=True))

    # Step 2: 将三列数据合并回 tokens
    op.execute(
        "UPDATE usage"
        " SET tokens = COALESCE(input_tokens, 0) + COALESCE(output_tokens, 0) + COALESCE(cached_tokens, 0)"
    )

    # Step 3: 删除三列
    with op.batch_alter_table("usage", schema=None) as batch_op:
        batch_op.drop_column("cached_tokens")
        batch_op.drop_column("output_tokens")
        batch_op.drop_column("input_tokens")
        batch_op.drop_column("model")

    # ### end Alembic commands ###
