"""add memory diary ledger and state

Revision ID: 5e446de27cb4
Revises: 3b6a7e5f332e
Create Date: 2026-09-12 19:38:43.481504

"""

from __future__ import annotations

from collections.abc import Sequence

import sqlalchemy as sa
from alembic import op

# revision identifiers, used by Alembic.
revision: str = "5e446de27cb4"
down_revision: str | Sequence[str] | None = "3b6a7e5f332e"
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "diary",
        sa.Column("id", sa.Integer(), autoincrement=True, nullable=False),
        sa.Column("source", sa.String(), nullable=False),
        sa.Column("day", sa.String(), nullable=False),
        sa.Column("content", sa.Text(), nullable=False),
        sa.Column("source_refs", sa.Text(), nullable=False),
        sa.Column("covered_through", sa.Integer(), nullable=False),
        sa.Column("created_at", sa.String(), nullable=False),
        sa.PrimaryKeyConstraint("id"),
        sa.UniqueConstraint("source"),
    )
    with op.batch_alter_table("diary", schema=None) as batch_op:
        batch_op.create_index(batch_op.f("ix_diary_day"), ["day"], unique=False)

    op.create_table(
        "experience",
        sa.Column("id", sa.Integer(), autoincrement=True, nullable=False),
        sa.Column("session_id", sa.String(), nullable=False),
        sa.Column("kind", sa.String(), nullable=False),
        sa.Column("content", sa.Text(), nullable=False),
        sa.Column("occurred_at", sa.String(), nullable=False),
        sa.Column("resources", sa.Text(), nullable=False),
        sa.Column("source", sa.String(), nullable=True),
        sa.PrimaryKeyConstraint("id"),
        sa.UniqueConstraint("source"),
    )
    with op.batch_alter_table("experience", schema=None) as batch_op:
        batch_op.create_index(batch_op.f("ix_experience_occurred_at"), ["occurred_at"], unique=False)
        batch_op.create_index(batch_op.f("ix_experience_session_id"), ["session_id"], unique=False)

    op.create_table(
        "fact",
        sa.Column("id", sa.Integer(), autoincrement=True, nullable=False),
        sa.Column("category", sa.String(), nullable=False),
        sa.Column("key", sa.String(), nullable=False),
        sa.Column("value", sa.Text(), nullable=False),
        sa.Column("active", sa.Boolean(), nullable=False),
        sa.Column("forgotten", sa.Boolean(), nullable=False),
        sa.Column("source_refs", sa.Text(), nullable=False),
        sa.Column("weight", sa.Float(), nullable=False),
        sa.Column("weight_at", sa.String(), nullable=False),
        sa.Column("observed_at", sa.String(), nullable=False),
        sa.Column("last_recalled_at", sa.String(), nullable=False),
        sa.Column("created_at", sa.String(), nullable=False),
        sa.PrimaryKeyConstraint("id"),
    )
    with op.batch_alter_table("fact", schema=None) as batch_op:
        batch_op.create_index(batch_op.f("ix_fact_category"), ["category"], unique=False)
        batch_op.create_index(batch_op.f("ix_fact_key"), ["key"], unique=False)

    op.create_table(
        "fact_recall",
        sa.Column("id", sa.Integer(), autoincrement=True, nullable=False),
        sa.Column("fact_id", sa.Integer(), nullable=False),
        sa.Column("day", sa.String(), nullable=False),
        sa.PrimaryKeyConstraint("id"),
        sa.UniqueConstraint("fact_id", "day"),
    )
    with op.batch_alter_table("fact_recall", schema=None) as batch_op:
        batch_op.create_index(batch_op.f("ix_fact_recall_fact_id"), ["fact_id"], unique=False)

    op.create_table(
        "memory_runtime",
        sa.Column("id", sa.Integer(), nullable=False),
        sa.Column("payload", sa.Text(), nullable=False),
        sa.PrimaryKeyConstraint("id"),
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table("memory_runtime")
    with op.batch_alter_table("fact_recall", schema=None) as batch_op:
        batch_op.drop_index(batch_op.f("ix_fact_recall_fact_id"))

    op.drop_table("fact_recall")
    with op.batch_alter_table("fact", schema=None) as batch_op:
        batch_op.drop_index(batch_op.f("ix_fact_key"))
        batch_op.drop_index(batch_op.f("ix_fact_category"))

    op.drop_table("fact")
    with op.batch_alter_table("experience", schema=None) as batch_op:
        batch_op.drop_index(batch_op.f("ix_experience_session_id"))
        batch_op.drop_index(batch_op.f("ix_experience_occurred_at"))

    op.drop_table("experience")
    with op.batch_alter_table("diary", schema=None) as batch_op:
        batch_op.drop_index(batch_op.f("ix_diary_day"))

    op.drop_table("diary")
    # ### end Alembic commands ###
