"""add node checkpoints schedules and executions

Revision ID: f25cd59dbab4
Revises: e262d3967ada
Create Date: 2026-10-02 14:14:15.534461

"""

from __future__ import annotations

from collections.abc import Sequence

import sqlalchemy as sa
from alembic import op

# revision identifiers, used by Alembic.
revision: str = "f25cd59dbab4"
down_revision: str | Sequence[str] | None = "e262d3967ada"
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "runtime_execution",
        sa.Column("id", sa.String(), nullable=False),
        sa.Column("node_id", sa.String(), nullable=False),
        sa.Column("epoch", sa.Integer(), nullable=False),
        sa.Column("payload", sa.Text(), nullable=False),
        sa.Column("status", sa.String(), nullable=False),
        sa.Column("result", sa.Text(), nullable=True),
        sa.PrimaryKeyConstraint("id"),
    )
    with op.batch_alter_table("runtime_execution", schema=None) as batch_op:
        batch_op.create_index(batch_op.f("ix_runtime_execution_node_id"), ["node_id"], unique=False)

    op.create_table(
        "runtime_schedule",
        sa.Column("id", sa.String(), nullable=False),
        sa.Column("payload", sa.Text(), nullable=False),
        sa.Column("due_at", sa.Float(), nullable=False),
        sa.Column("occurrence", sa.Integer(), nullable=False),
        sa.Column("enabled", sa.Boolean(), nullable=False),
        sa.PrimaryKeyConstraint("id"),
    )
    with op.batch_alter_table("runtime_schedule", schema=None) as batch_op:
        batch_op.create_index(batch_op.f("ix_runtime_schedule_due_at"), ["due_at"], unique=False)

    op.create_table(
        "runtime_state",
        sa.Column("id", sa.Integer(), nullable=False),
        sa.Column("payload", sa.Text(), nullable=False),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_table(
        "runtime_turn",
        sa.Column("id", sa.String(), nullable=False),
        sa.Column("generations", sa.Text(), nullable=False),
        sa.Column("completed", sa.Boolean(), nullable=False),
        sa.Column("commit_digest", sa.String(), nullable=True),
        sa.PrimaryKeyConstraint("id"),
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table("runtime_turn")
    op.drop_table("runtime_state")
    with op.batch_alter_table("runtime_schedule", schema=None) as batch_op:
        batch_op.drop_index(batch_op.f("ix_runtime_schedule_due_at"))

    op.drop_table("runtime_schedule")
    with op.batch_alter_table("runtime_execution", schema=None) as batch_op:
        batch_op.drop_index(batch_op.f("ix_runtime_execution_node_id"))

    op.drop_table("runtime_execution")
    # ### end Alembic commands ###
