"""first revision

迁移 ID: 8cc5f266417d
父迁移:
创建时间: 2026-03-04 22:14:38.637123

"""

from __future__ import annotations

from collections.abc import Sequence

import sqlalchemy as sa
from alembic import op

revision: str = "8cc5f266417d"
down_revision: str | Sequence[str] | None = None
branch_labels: str | Sequence[str] | None = ("muika",)
depends_on: str | Sequence[str] | None = None


def upgrade(name: str = "") -> None:
    if name:
        return
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "muika_archiverecordorm",
        sa.Column("id", sa.Integer(), autoincrement=True, nullable=False),
        sa.Column("session_id", sa.String(), nullable=False),
        sa.Column("summary", sa.Text(), nullable=False),
        sa.Column("period_start", sa.String(), nullable=False),
        sa.Column("period_end", sa.String(), nullable=False),
        sa.Column("created_at", sa.String(), nullable=False),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_muika_archiverecordorm")),
        info={"bind_key": "muika"},
    )
    with op.batch_alter_table("muika_archiverecordorm", schema=None) as batch_op:
        batch_op.create_index(
            batch_op.f("ix_muika_archiverecordorm_session_id"),
            ["session_id"],
            unique=False,
        )

    op.create_table(
        "muika_memoryrecordorm",
        sa.Column("id", sa.Integer(), autoincrement=True, nullable=False),
        sa.Column("layer", sa.String(), nullable=False),
        sa.Column("category", sa.String(), nullable=False),
        sa.Column("key", sa.String(), nullable=False),
        sa.Column("value", sa.Text(), nullable=False),
        sa.Column("created_at", sa.String(), nullable=False),
        sa.Column("updated_at", sa.String(), nullable=False),
        sa.Column("expires_at", sa.String(), nullable=True),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_muika_memoryrecordorm")),
        info={"bind_key": "muika"},
    )
    with op.batch_alter_table("muika_memoryrecordorm", schema=None) as batch_op:
        batch_op.create_index(batch_op.f("ix_muika_memoryrecordorm_key"), ["key"], unique=False)
        batch_op.create_index(batch_op.f("ix_muika_memoryrecordorm_layer"), ["layer"], unique=False)

    op.create_table(
        "muika_usage",
        sa.Column("id", sa.Integer(), autoincrement=True, nullable=False),
        sa.Column("plugin", sa.String(), nullable=False),
        sa.Column("type", sa.String(), nullable=False),
        sa.Column("date", sa.String(), nullable=False),
        sa.Column("tokens", sa.Integer(), nullable=True),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_muika_usage")),
        info={"bind_key": "muika"},
    )
    # ### end Alembic commands ###


def downgrade(name: str = "") -> None:
    if name:
        return
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table("muika_usage")
    with op.batch_alter_table("muika_memoryrecordorm", schema=None) as batch_op:
        batch_op.drop_index(batch_op.f("ix_muika_memoryrecordorm_layer"))
        batch_op.drop_index(batch_op.f("ix_muika_memoryrecordorm_key"))

    op.drop_table("muika_memoryrecordorm")
    with op.batch_alter_table("muika_archiverecordorm", schema=None) as batch_op:
        batch_op.drop_index(batch_op.f("ix_muika_archiverecordorm_session_id"))

    op.drop_table("muika_archiverecordorm")
    # ### end Alembic commands ###
