"""first revision

迁移 ID: c3be6a457f78
父迁移:
创建时间: 2026-02-01 18:30:07.237191

"""

from __future__ import annotations

from collections.abc import Sequence

import sqlalchemy as sa
from alembic import op

revision: str = "c3be6a457f78"
down_revision: str | Sequence[str] | None = None
branch_labels: str | Sequence[str] | None = ("muika",)
depends_on: str | Sequence[str] | None = None


def upgrade(name: str = "") -> None:
    if name:
        return
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "muika_usage",
        sa.Column("id", sa.Integer(), autoincrement=True, nullable=False),
        sa.Column("plugin", sa.String(), nullable=False),
        sa.Column("type", sa.String(), nullable=False),
        sa.Column("date", sa.String(), nullable=False),
        sa.Column("tokens", sa.Integer(), nullable=True),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_muika_usage")),
        info={"bind_key": "muika"},
    )
    # ### end Alembic commands ###


def downgrade(name: str = "") -> None:
    if name:
        return
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table("muika_usage")
    # ### end Alembic commands ###
