"""add TopicHistory

迁移 ID: d13b6e321e0c
父迁移: 8cc5f266417d
创建时间: 2026-03-08 16:39:10.872590

"""

from __future__ import annotations

from collections.abc import Sequence

import sqlalchemy as sa
from alembic import op

revision: str = "d13b6e321e0c"
down_revision: str | Sequence[str] | None = "8cc5f266417d"
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade(name: str = "") -> None:
    if name:
        return
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "muika_topichistoryorm",
        sa.Column("id", sa.Integer(), autoincrement=True, nullable=False),
        sa.Column("topic_id", sa.String(), nullable=False),
        sa.Column("last_used_at", sa.String(), nullable=False),
        sa.Column("use_count", sa.Integer(), nullable=False),
        sa.Column("engaged_count", sa.Integer(), nullable=False),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_muika_topichistoryorm")),
        info={"bind_key": "muika"},
    )
    with op.batch_alter_table("muika_topichistoryorm", schema=None) as batch_op:
        batch_op.create_index(batch_op.f("ix_muika_topichistoryorm_topic_id"), ["topic_id"], unique=True)
    # ### end Alembic commands ###


def downgrade(name: str = "") -> None:
    if name:
        return
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table("muika_topichistoryorm", schema=None) as batch_op:
        batch_op.drop_index(batch_op.f("ix_muika_topichistoryorm_topic_id"))

    op.drop_table("muika_topichistoryorm")
    # ### end Alembic commands ###
